# Generated by Django 4.2.23 on 2025-07-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_alter_department_director'),
        ('request', '0007_alter_request_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_for_department', to='department.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='request',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado'),
        ),
    ]
